# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://c7.se
title: Code7 Interactive
author: Peter Hellberg

# ----------------------- #
#    Jekyll               #
# ----------------------- #

source: site
destination: .public

safe:        true
pygments:    true
lsi:         false

markdown:    rdiscount
rdiscount:
  extensions: [smart]

permalink: /:title/

# Google Analytics
google_analytics_tracking_id: UA-940629-1
